export const SHEET_PUB_BASE = "https://docs.google.com/spreadsheets/d/e/2PACX-1vT1ILHR8Hehw4FiGRKgTm__paCyusHvn5LcHlOeFtZAxENpO8GKr2MzV6s1iX7R8e1KbTJqYOCWIMTU/pub";
export const HISTORICO_URL = `${SHEET_PUB_BASE}?gid=1453444709&single=true&output=csv`;
export const AUTORIZADORES_URL = `${SHEET_PUB_BASE}?gid=1684740922&single=true&output=csv`;

// ⚠️ Pega aquí la URL del despliegue del Apps Script (termina en /exec)
// Instrucciones en README_SETUP.md
export const APPS_SCRIPT_URL = "PEGA_AQUI_LA_URL_DEL_WEBAPP_APPS_SCRIPT";

export const COPEC_EXCLUSIONS = new Set([
  "COPEC S A","COPEC S A (LUBRICANTES)","COPEC S A (LUBRICANTES)(NOTA DE CREDITO)",
  "ESMAX DISTRIBUCION SPA","FLUX SOLAR ENERGIAS RENOVABLES SPA",
  "COPEC S A (NOTA DE CREDITO)","COPEC S A (NOTA DE CREDITO)(LUBRICANTES)",
  "ESMAX DISTRIBUCION SPA (NOTA DE CREDITO)","FLUX SOLAR ENERGIAS RENOVABLES SPA (NOTA DE CREDITO)"
]);

export const CUOTA_RULES = {
  "MICHELIN CHILE LTDA":2,"MICHELIN CHILE LTDA (NOTA DE CREDITO)":2,
  "AC COMERCIAL SPA":2,"COMERCIAL SP LTDA":2,
  "BOLSA DE PRODUCTOS DE CHILE (MILLA TIRES)":2,"SKC Servicios Automotrices S.A.":2,
  "Goodyear de Chile S.A.I.C":3,"Goodyear de Chile S.A.I.C (NOTA DE CREDITO)":3,
  "SALINAS Y FABRES S.A.":3,"SKC RED SPA":3,"SKC RED S.A.":3,
  "BPC SERVICIOS Y NEGOCIOS S.A. (MILLA TIRES)":3,
  "CAREN SPA":3,"COMERCIALIZADORA DE NEUMATICOS LIMITADA":3,
  "Supermercado del Neumático Ltda.":3,"Milla Tirers Co Limitada":3,
  "FACTOTAL S A (MILLA TIRES)":3,"RED CAPITAL S.A. (MILLA TIRES)":3,
  "BANPRO FACTORING S.A (MILLA TIRES)":3,
  "CAPITAL EXPRESS SERVICIOS FINANCIEROS S.A. (MILLA TIRES)":3,
  "LATAM TRADE CAPITAL S.A. (MILLA TIRES)":3,
  "TANNER SERVICIOS FINANCIEROS S.A. (MILLA TIRES)":3,
};

export const AUTH_LIST = ["MBL","LBS","LBL","PR","HB","NG","RB","LP","PB"];

export const REMOVE_COLS = [
  'Cuenta','Descripción','Clasificador 1 (NOMINA_PROV)',
  'Cód. Elemento 1','Desc. Elemento 1'
];
